server:
  port: ${URLCLEANER_PORT}

bpbridge:
  root: ${BPBRIDGE_IP}
  getRandomOfferRoute: '/getRandomOffers'
  shopIDToURLRoute: '/shopIDToUrl'
  matchAttributeRoute: '/matchAttribute'

urlcleaner:
  root: '/'
  cleanURLRoute: '/cleanURL'